version: '3'
services:
  registry:
    image: "diamondpkg/registry:latest"
    restart: always
    container_name: registry
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - DIALECT=postgres
      - DB=registry
      - HOST=registry_db
      - USER=username
      - PASSWORD=password
  registry_db:
    image: "postgres:9"
    container_name: registry_db
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password